# Generated by Django 4.0.2 on 2022-03-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='name',
        ),
    ]
