# Generated by Django 4.0.2 on 2022-03-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_navbar_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat1', models.BooleanField()),
                ('long1', models.BooleanField()),
                ('lat2', models.BooleanField()),
                ('long2', models.BooleanField()),
            ],
        ),
    ]
