# Generated by Django 4.0.2 on 2022-03-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_route_lat1_alter_route_lat2_alter_route_long1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='NavBar',
        ),
    ]
