# Generated by Django 4.0.2 on 2022-05-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_logo_delete_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
