# Generated by Django 4.0.2 on 2022-05-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_profile_delete_user'),
        ('main', '0009_remove_route_lat1_remove_route_lat2_and_more'),
    ]

    operations = [
    ]
