# Generated by Django 4.0.2 on 2022-05-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20220503_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='IdOwner',
            field=models.IntegerField(null=True),
        ),
    ]
