# Generated by Django 4.0.2 on 2022-05-05 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_register_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='IdOwner',
            new_name='Owner',
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='route',
            name='petfriendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
