# Generated by Django 4.0.2 on 2022-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_idowner_route_owner_route_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
