# Generated by Django 4.0.2 on 2022-05-05 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_route_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
