# Generated by Django 4.0.2 on 2022-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_route_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
