# Generated by Django 4.0.2 on 2022-05-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_route_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='participants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
