# Generated by Django 4.0.2 on 2022-05-18 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_route_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
