# Generated by Django 4.0.2 on 2022-05-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_route_starttime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
