# Generated by Django 4.0.2 on 2022-05-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='participants',
            field=models.JSONField(blank=True, default='{"waiting":[],"accepted":[]}'),
        ),
    ]
