# Generated by Django 4.0.2 on 2022-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_route_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
